<?php
/**
 * Created by PhpStorm.
 * User: Capliez
 * Date: 03/04/2019
 * Time: 11:37
 */

namespace AppBundle\Repository;

/**
 * ChoixRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChoixRepository extends \Doctrine\ORM\EntityRepository
{

}