<?php

namespace AppBundle\Repository;

/**
 * PasserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasserRepository extends \Doctrine\ORM\EntityRepository
{
}
