<?php

namespace AppBundle\Repository;

/**
 * PropositionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropositionRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $eleve_id
     */
    public function findByProposition($eleve_id)
    {
        $conn = $this->getEntityManager()->getConnection();

        $sql = '
            SELECT * FROM proposition p
            WHERE p.eleve_id LIKE :eleve_id
            ';
        $stmt = $conn->prepare($sql);
        $stmt->execute(['eleve_id' => $eleve_id]);

        return $stmt->fetchAll();
    }
}