# app/config/security.yml

security:
    encoders:
        AppBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
        ROLE_CONSULTANT : ROLE_CONSULTANT
        ROLE_USER:        ROLE_USER
        ROLE_ELEVE:       ROLE_ELEVE #Rôle par défaut !!
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ELEVE, ROLE_USER, ROLE_ALLOWED_TO_SWITCH, ROLE_CONSULTANT] # A ne pas utliser

    providers:
        main:
            id: fos_user.user_provider.email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false  
        main:
            pattern:   ^/
            provider: main
            form_login:
                csrf_token_generator: security.csrf.token_manager
                login_path: fos_user_security_login
                check_path: fos_user_security_check  
                use_referer: true
                remember_me: true
                default_target_path: /
            logout:          true
            anonymous:       true
            remember_me:
                lifetime: 604800 # 1 week in seconds
                secret:     %secret% # %secret% est un paramètre de parameter
            switch_user:     true
        login:
            pattern: ^/(login$|register|resetting)
            anonymous: true  

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: ROLE_ADMIN } # Accessible par les administrateurs (route désactiver)
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/eleve/, role: ROLE_ELEVE } # Accessible par les éléves
        - { path: ^/admin/, role: ROLE_ADMIN } # Accessible par les administrateurs
        - { path: ^/consultant/, role: ROLE_CONSULTANT } # Accessible par les consultants





