<?php

namespace AppBundle\Repository;

/**
 * ExaminateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExaminateurRepository extends \Doctrine\ORM\EntityRepository
{
}
